name: Update README with recent activity
on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 10
