name: Update Codeforces solved count

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Compute solved count from Codeforces API
        id: cf
        run: |
          handle=moohameed
          url="https://codeforces.com/api/user.status?handle=$handle&from=1&count=100000"
          json=$(curl -s "$url")
          solved=$(echo "$json" | jq -r '.result | map(select(.verdict=="OK")) | map(.problem.contestId|tostring + ":" + .problem.index) | unique | length')
          echo "solved=$solved" >> $GITHUB_OUTPUT
      - name: Update README marker
        run: |
          file="README.md"
          solved="${{ steps.cf.outputs.solved }}"
          perl -0777 -pe "s/(<!-- CF_SOLVED_START -->)(.*?)(<!-- CF_SOLVED_END -->)/\1${solved}\3/s" -i "$file"
      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update Codeforces solved count to ${{ steps.cf.outputs.solved }}"
          git push
